#! /usr/bin/env node

const fs = require('fs');
const path = require('path');

// Get the function name from the first argument
const functionName = process.argv[2];

// Get the function path from the second argument
const functionPath = process.argv[3];

// Get repo root
const { execSync } = require('child_process');
const repoRoot = execSync('git rev-parse --show-toplevel').toString().trim();

// Update the function path in index.js
const indexPath = path.join(repoRoot, 'netlify/functions/serverless/index.js');
let indexContent = fs.readFileSync(indexPath, 'utf8');
indexContent = indexContent.replace(/functionsDir: "\.\.\/netlify\/functions"/g, 'functionsDir: "./netlify/functions"');
fs.writeFileSync(indexPath, indexContent, 'utf8');

// Update the function path in eleventy.config.js
const eleventyConfigPath = path.join(repoRoot, 'netlify/functions/serverless/eleventy.config.js');
let eleventyConfigContent = fs.readFileSync(eleventyConfigPath, 'utf8');
eleventyConfigContent = eleventyConfigContent.replace(/functionsDir: "\.\.\/netlify\/functions"/g, 'functionsDir: "./netlify/functions"');
fs.writeFileSync(eleventyConfigPath, eleventyConfigContent, 'utf8');
