backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: Behold Feed URL, name: beholdFeedUrl, widget: string }

  - label: "People"
    name: "people"
    folder: src/people
    create: true
    identifier_field: name
    fields:
      - { label: Name, name: name, widget: string } 
      - { label: Role, name: role, widget: string } 
      - { label: Picture, name: picture, widget: image }
      - { label: Body, name: body, widget: markdown }


