[build]
publish = "web/_site"
command = "nx run @our-moving-stories/web:build"

[functions]
directory = "web/netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["uglify-js"]

[[redirects]]
from = "/safeguarding-policy/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/:slug/"
to = "/.netlify/functions/serverless"
status = 200
force = true
